language: go
go: 1.9
os:
  - linux
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq devscripts build-essential dh-make
  - git clone https://github.com/subutai-io/p2p-packages.git $P2P_PACKAGE_DIR
  - openssl aes-256-cbc -K $encrypted_62c1e8a94b65_key -iv $encrypted_62c1e8a94b65_iv -in $P2P_PACKAGE_DIR/secret.key.enc -out /tmp/p2p-packages/secret.key -d
  - gpg --import $P2P_PACKAGE_DIR/secret.key && rm -f $P2P_PACKAGE_DIR/secret.key*
install:
  - go get
  - go get golang.org/x/sys/windows
script:
  - if [ ! -z "$TRAVIS_TAG" ] ; 
    then ./configure --branch=HEAD ; 
    else ./configure --branch=$TRAVIS_BRANCH ;
    fi
  - make all
  - make test
  - if [ ! -z "$TRAVIS_TAG" ] ; 
    then cd $P2P_PACKAGE_DIR && ./configure --debian --branch=HEAD ; 
    else cd $P2P_PACKAGE_DIR && ./configure --debian --branch=$TRAVIS_BRANCH ;
    fi
  - cd $P2P_PACKAGE_DIR/linux && cp ${TRAVIS_BUILD_DIR}/bin/p2p $P2P_PACKAGE_DIR/linux/debian/ && debuild -B -d
  - $P2P_PACKAGE_DIR/extra/find-deb.sh $P2P_PACKAGE_DIR/linux $P2P_PACKAGE_DIR/subutai-p2p
  - if [ ! -z "$TRAVIS_TAG" ] ; 
    then cd $P2P_PACKAGE_DIR && ./configure --darwin --branch=HEAD ; 
    else cd $P2P_PACKAGE_DIR && ./configure --darwin --branch=$TRAVIS_BRANCH ;
    fi
  - cd $P2P_PACKAGE_DIR/darwin && ./pack.sh ${TRAVIS_BUILD_DIR}/bin/p2p_osx
  - $P2P_PACKAGE_DIR/deploy.sh $P2P_PACKAGE_DIR/subutai-p2p HEAD .deb-travis-test ; 
  - cd ${TRAVIS_BUILD_DIR}
deploy:
  - provider: script
    script: $P2P_PACKAGE_DIR/deploy.sh bin/p2p dev -travis-test
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script: $P2P_PACKAGE_DIR/deploy.sh bin/p2p_osx dev -travis-test
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script: $P2P_PACKAGE_DIR/deploy.sh bin/p2p.exe dev -travis-test
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script: $P2P_PACKAGE_DIR/deploy.sh bin/p2p master -travis-test
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: $P2P_PACKAGE_DIR/deploy.sh bin/p2p_osx master -travis-test
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: $P2P_PACKAGE_DIR/deploy.sh bin/p2p.exe master -travis-test
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: $P2P_PACKAGE_DIR/deploy.sh bin/p2p HEAD -travis-test
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: $P2P_PACKAGE_DIR/deploy.sh bin/p2p_osx HEAD -travis-test
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: $P2P_PACKAGE_DIR/deploy.sh bin/p2p.exe HEAD -travis-test
    skip_cleanup: true
    on:
      tags: true
notifications:
  slack:
    secure: oshkIoOJGMJ8iwmtgaSvkelCM5GIMld9jy7ZjUy9vATpsiOntAovhEFtlpmxnok1mD53SV1m45mPY7JnNOKjFOMQA3hFANEN79RSGjQKI5JNqGTRLsDuFmbgUPoS3lyV8qTdyytKOpi1moaVOsSD8s3byzmdWHMtnkS6M8iS5+3L/t3o6W7lNDSdFJCPDtVxIFrH+CBRRMbbFFkhPOxmJSxBaxEN7EEpNAwgw6z2pOqSj6fD5vwXG5YcuH6/cWEmAiVC4hIfxERh2cMGzCkgl4ZpO12AQvJBLw9ufhLvu2ER03fhqkKuHAo7myF0PcqSpOFhdamO05MtiWN/6RLGHDMIWRfBmaYmOfPyaodSUF4DZrhFYmMXDXhWkrpeBpYzknPQqPkwouYO6OtHsdMITdo27n1ENg1QuIth8kjiPbVcz/gjsUTzkcbbbQQw4LGcdkj6NawC3oq7+JXUE4gIGiqpuMEIxaKIe+P/77nIxVqGOQUQJzVx2IQKG8dBKUpBeFkTnDoJxbT/u7Q2cIMtv/Tmv+m7uEvii/kwrsk/XJpBWL3xzSgmiCiTi346bbJ71lFeuBpiYEN9P3Afi/573Bxddj7eA23ricF81QrBHTpo7OnrwKPz+dz8g7/297rWJC80olemkdFyp3bjgd158TKepYU+YP/LLugRF+AVLJQ=
