language: go

go: 1.5

go_import_path: github.com/

script: go get github.com/danderson/tuntap && go get github.com/mdlayher/ethernet && go get gopkg.in/yaml.v2 && go get github.com/jackpal/bencode-go && go get github.com/wayn3h0/go-uuid && go test ./...
