version: "{build}"

clone_folder: c:\root\src\github.com\subutai-io\p2p

environment:
  GOPATH: c:\root
  DEPTESTBYPASS501: 1
  GOVERSION: 1.9

install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - choco install bzr
  - set Path=c:\go\bin;c:\root\bin;C:\Program Files (x86)\Bazaar\;C:\Program Files\Mercurial\%Path%
  - go version
  - go env
  - git clone --depth 1 https://github.com/subutai-io/p2p-packages.git c:\root\p2p-packages
  - curl -fsSLk https://eu0.cdn.subutai.io:8338/kurjun/rest/raw/get?name=tap-windows-9.21.2.exe -o c:\root\p2p-packages\tap-windows-9.21.2.exe
  - curl -fsSLk https://files.gpg4win.org/gpg4win-3.0.3.exe -o c:\root\gpg4win.exe
  - echo c:\root\gpg4win.exe /S
  - gpg --list-keys

before_build:
  - C:\msys64\usr\bin\bash -lc "$(cygpath ${APPVEYOR_BUILD_FOLDER})/configure"

build_script: 
  - cmd: >-
      type config.make

      go get

      go build github.com/subutai-io/p2p

      c:\root\src\github.com\subutai-io\p2p\p2p.exe -v

      copy c:\root\src\github.com\subutai-io\p2p\p2p.exe c:\root\p2p-packages\p2p.exe

      "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\Common7\\IDE\\devenv.exe" c:\\root\\p2p-packages\\windows\\win.sln /Rebuild Release

deploy_script:
  - echo 1

notifications:
  - provider: Slack
    incoming_webhook:
      secure: EH0gGIsLRLevwZRtCfJVMO6Bw+OP7p+1eyWatC0h6IorO7ksOj+PsENn5duSz59F45IIrPB0c318ZAzXGEhiUhD/Huor6zS/mQfejsO5RTg=
